//! File generated by AI not verified by a human yet
//!
//! Minimal test to verify macro expansion works

use easy_macros_all_syntax_cases::all_syntax_cases;
use quote::ToTokens;
use syn::parse_quote;

#[derive(Default, Debug)]
struct SimpleContext {
    count: usize,
}

all_syntax_cases! {
    setup => {
        generated_fn_prefix: "simple",
        additional_input_type: &mut SimpleContext
    }
    default_cases => {
        fn simple_handler(expr: &mut syn::Expr, ctx: &mut SimpleContext);
    }
    special_cases => {
        fn dummy_special_unused(item_fn: &mut syn::ItemFn, ctx: &mut SimpleContext);
    }
}

fn simple_handler(_expr: &mut syn::Expr, ctx: &mut SimpleContext) {
    ctx.count += 1;
}

fn dummy_special_unused(_item_fn: &mut syn::ItemFn, _ctx: &mut SimpleContext) {
    // Unused dummy to satisfy macro requirements
}

#[test]
fn test_macro_expands() {
    let mut ctx = SimpleContext::default();
    let mut expr: syn::Expr = parse_quote! { 1 + 2 };

    simple_expr_handle(&mut expr, &mut ctx);

    println!("Count: {}", ctx.count);
    assert!(ctx.count > 0, "Handler should have been called");
}
