use always_context::always_context;
use anyhow::Context;
use helpers_context::context;
use helpers_macro_safe::{MacroResult, find_crate_list, indexed_name, parse_macro_input};
use proc_macro::TokenStream;
use quote::quote;

use crate::{
    context_crate,
    data::{AttrWithUnknown, HandleAttrsInput},
    root_macros_crate,
};

fn external_crate_parent() -> proc_macro2::TokenStream {
    if let Some(found) = find_crate_list(&[("easy-lib", quote! {}), ("easy-macros", quote! {})]) {
        found
    } else {
        quote! {}
    }
}

#[always_context]
pub fn get_attributes(item: TokenStream) -> anyhow::Result<TokenStream> {
    let parsed = parse_macro_input!(item as HandleAttrsInput);
    //The easiest way would be just turning attributes into a string and then parsing it
    //We would have to parse some parts into string anyway and this isn't performance critical

    let external_crate = external_crate_parent();

    let operate_on = parsed.operate_on;
    let mut attributes = parsed.attributes;
    let mut result = MacroResult::default();

    let unknown_attr = {
        let mut unknown_attr = None;
        let mut to_remove = None;
        for (index, attr) in attributes.iter().enumerate() {
            if unknown_attr.is_none() {
                if AttrWithUnknown::new(attr)?.is_some() {
                    unknown_attr = Some(attr.clone());
                    to_remove = Some(index);
                }
            } else {
                //There can only be one unknown
                anyhow::bail!("Multiple unknowns found in attributes!");
            }
        }
        if let Some(index) = to_remove {
            attributes.remove(index);
        }
        if let Some(attr) = unknown_attr {
            attr
        } else {
            anyhow::bail!("No unknown found in (to search for) attributes!");
        }
    };

    let attributes_len = attributes.len();
    let attr_to_find_vars = indexed_name(quote::format_ident!("attr_to_find"), attributes_len);
    let found_vars = indexed_name(quote::format_ident!("found_vars"), attributes_len);

    //Start if statement to check if attributes are present
    if attributes_len > 0 {
        //Check if attributes are present
        let mut maybe_break = quote! {};
        //Add break; if only one attribute is passed in
        if attributes_len == 1 {
            maybe_break = quote! { break; };
        }

        result.add(quote! {
            if {
                #(
                    let #attr_to_find_vars:#external_crate::syn::Attribute = #external_crate::syn::parse_quote! {
                        #attributes
                    };
                    let mut #found_vars = false;
                )*
                for attr in #operate_on.attrs.iter() {
                    #(
                        if attr == &#attr_to_find_vars {
                            #found_vars = true;
                            #maybe_break
                        }
                    )*
                }
                let mut found=true;
                #(
                    if !#found_vars {
                        found=false;
                    }
                )*
                found
            }
        });
    }

    let crate_root = root_macros_crate();
    let context_crate = context_crate();

    //if statement block or just standalone block
    result.add(quote! {
        {
            use #external_crate::quote::ToTokens;
            let u_attr:#external_crate::syn::Attribute = #external_crate::syn::parse_quote!{#unknown_attr};
            let unknown = #crate_root::AttrWithUnknown::new(&u_attr)
            .with_context(#context_crate::context!("(generated by get_attributes macro, this error should be unreachable)\r\nAttrWithUnknown::new(#unknown_attr)\r\n\r\nunknown_attr: {}",u_attr.to_token_stream()))?
            .with_context(#context_crate::context!("(generated by get_attributes macro, this error should be unreachable)\r\nSome Expected, got None\r\nAttrWithUnknown::new(#unknown_attr)\r\n\r\nunknown_attr: {}",u_attr.to_token_stream()))?;

            let mut unknown_replacers = Vec::new();
            for attr in #operate_on.attrs.iter() {
                if let Some(u) = unknown.get_unknown(attr).with_context(#context_crate::context!("unknown.get_unknown(attr)\r\n\r\nattr: {}\r\n\r\nunknown: {:?}",attr.to_token_stream(),unknown))?{
                    unknown_replacers.push(u);
                }
            }
            unknown_replacers
        }
    });
    //Add else statement and brace result if attributes are present
    if attributes_len > 0 {
        result.add(quote! {
            else {
                vec![]
            }
        });
        result.braced();
    }

    // panic!("{}", result.finalize());

    Ok(result.finalize().into())
}
